### ISSUE TITLE
Curfew Enabled error in logs

### ISSUE THREAD

**Issue by alphamaestro555** [PetHubLocal/pethublocal#21]
I try to set up pethublocal in Docker and ran into some issues. I unknowingly did a firmware upgrade from 2.43 to 2.201 by thinking I could reset the hub to resolve the issues. Then I found out I had to downgrade the firmware, which I did and it seemed to be successful.

I can see the pethublocal container connects to my Mosquitto instance, and I can see the sensors and switches in MQTT explorer as well as in Home Assistant. But in HA I cannot control the switches or see the sensors.

The hub also connects to my Mosquitto instance so all certs are set up correctly, and the ears of the hub are not blinking anymore.

I have changed the HTTPS host in pethubconfig.json to the container IP and I can access the web interface. But no pets are listed there.

In the Mosquitto logs I can see PetHubLocal connects but then disconnects:

```
2022-12-23 23:04:50: New connection from 192.168.x.x:33985 on port 1883.
2022-12-23 23:04:50: New client connected from 192.168.x.x:33985 as PetHubLocal (p2, c1, k60).
2022-12-23 23:04:56: Client PetHubLocal disconnected.
```

And in theconsole for the pethublocal container I get the following errors:

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-2' coro=<mqtt_start() done, defined at /usr/local/lib/python3.9/site-packages/pethublocal/frontend.py:199> exception=BoxKeyError("'Box' object has no attribute 'Curfew_Enabled'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/box/box.py", line 504, in __getitem__
    return super().__getitem__(item)
KeyError: 'Curfew_Enabled'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/box/box.py", line 537, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/usr/local/lib/python3.9/site-packages/box/box.py", line 525, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'Curfew_Enabled'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/box/box.py", line 539, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'Box' object has no attribute 'Curfew_Enabled'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pethublocal/frontend.py", line 243, in mqtt_start
    ha_init_state = ha_update_state(app['pethubconfig'])
  File "/usr/local/lib/python3.9/site-packages/pethublocal/functions.py", line 899, in ha_update_state
    elif attrs.Product_Id == 6 and attrs.Curfew_Enabled == 1:
  File "/usr/local/lib/python3.9/site-packages/box/box.py", line 553, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'Box' object has no attribute 'Curfew_Enabled'"
```
I have tried to remove the following lines in the pethubconfig.json but without any result, the error still show up.
```
"Curfew_Enabled": true,
"Curfews": "21:30-05:00",
```
Those curfews were set via the app before when I had it connected to Sure Petcare cloud. But then their service stopped working suddenly and I couldnt remove the curfews.

Does anybody have ideas that can lead me in the right direction on how to get it up and running?

**Comment by alphamaestro555** [comment]
I have two cat doors and in the config block there was missing two lines.
By adding those two lines the problem got solved.
```
"Curfew_Enabled": true,
"Curfews": "21:30-05:00",
```
