### ISSUE TITLE
 emit() got an unexpected keyword argument 'broadcast'

### ISSUE THREAD

**Issue by Flachzange** [PetHubLocal/pethublocal#26]
For some I reason I rebuild the docker image. After that I noticed an error message after powering up the hub:

> 023-05-21 10:27:37.218257+00:00ERROR:asyncio:Task exception was never retrieved
> 2023-05-21 10:27:37.218328+00:00future: <Task finished name='Task-2' coro=<mqtt_start() done, defined at /usr/local/lib/python3.9/site-packages/pethublocal/frontend.py:204> exception=TypeError("emit() got an unexpected keyword argument 'broadcast'")>
> 2023-05-21 10:27:37.218349+00:00Traceback (most recent call last):
> 2023-05-21 10:27:37.218364+00:00File "/usr/local/lib/python3.9/site-packages/pethublocal/frontend.py", line 295, in mqtt_start
> 2023-05-21 10:27:37.218391+00:00await asyncio.gather(*tasks)
> 2023-05-21 10:27:37.218407+00:00File "/usr/local/lib/python3.9/site-packages/pethublocal/frontend.py", line 345, in parse_message
> 2023-05-21 10:27:37.218434+00:00await sio.emit('web_message', data=parsed_result, broadcast=True, include_self=False)
> 2023-05-21 10:27:37.218471+00:00TypeError: emit() got an unexpected keyword argument 'broadcast'
> 2023-05-21 10:28:02.803311+00:00packet queue is empty, aborting
> 2023-05-21 10:28:02.803426+00:00ERROR:engineio.client:packet queue is empty, aborting
> 2023-05-21 10:28:17.813610+00:00INFO:pethublocal:SIO: Disconnect 4LQdV6Z5IXvRj4dnAAAB

This seems to be caused by a breaking change introduced by socketio 5.8.0. Quick fix is to change the version requirements in pyproject.toml

`python-socketio = "<=5.7.8"
`

**Comment by plambrechtsen** [comment]
I have been thinking about this as I have parked the code for ages as everything has been working fine for me. Long weekend here so I will take a look. Appreciate the feedback and sorry I have had this parked for a year.

**Comment by C0NTi** [comment]
@Flachzange Thank you! That did the trick, its working again. 
I recently moved to a new server so had to build everything from scratch, it was bugging me that it would work on the old server but not the new one!

**Comment by plambrechtsen** [comment]
Closing this issue as I now have a whole new approach. This python code is great for a reference but I won't be making any changes to it going forward. If you are interested in my new approach send me an email pethublocal at gmail . com.
