### ISSUE TITLE
Unable to Download Credentials and Firmware for Hub

### ISSUE THREAD

**Issue by ziogref** [PetHubLocal/pethublocal#33]
On both my Home assistant server and my laptop I am unable to download the Firmware for the pet hub. 

Here is the console output from the docker container when running pethublocal setup

`Download Credentials and Firmware for Hub (highly recommended)? Y/N y
INFO:pethublocal:Current Hub Firmware 233.364
INFO:pethublocal:Downloading Current Firmware for H010-0807262
INFO:pethublocal:SureHub Host hub.api.surehub.io IP Address: 15.197.140.15
INFO:pethublocal:Downloading first firmware record to get header information
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 15.197.140.15:80
DEBUG:urllib3.connectionpool:http://15.197.140.15:80 "POST /api/firmware HTTP/1.1" 400 None
Traceback (most recent call last):
  File "/usr/local/bin/pethublocal", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pethublocal/cli/__init__.py", line 72, in setup
    pethubconfig = config_load(True, force)
  File "/usr/local/lib/python3.9/site-packages/pethublocal/functions.py", line 379, in config_load
    log.info(download_firmware(serial_number, force))
  File "/usr/local/lib/python3.9/site-packages/pethublocal/functions.py", line 99, in download_firmware
    download_firmware_record(surehubio, serialnumber, BOOTLOADER, 0)
  File "/usr/local/lib/python3.9/site-packages/pethublocal/functions.py", line 78, in download_firmware_record
    response.raise_for_status()  # Ensure we notice bad responses
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://15.197.140.15/api/firmware
`

**Comment by flyize** [comment]
IIRC, @plambrechtsen said they no longer post it. As it stands, this repo no longer works with hubs on the current firmware.

**Comment by ziogref** [comment]
> IIRC, @plambrechtsen said they no longer post it. As it stands, this repo no longer works with hubs on the current firmware.

Ah that sucks. Might have to keep an eye out for the ESP32 mentioned on issue #31

**Comment by plambrechtsen** [comment]
In closing this as SurePetCare have done a firmware update to lock me out.
But I have an all new approach I am working on so then needing the credentials will no longer be required.
