### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by pounard** [PetHubLocal/pethublocal#35]
Hello!

Latest commit is now 1 year-ish old, and there is not much activity in issue queue, is this still maintained?

**Comment by flyize** [comment]
Essentially, no

**Comment by pounard** [comment]
Thank you for answering! Is there any alternatives?

**Comment by jacotec** [comment]
Let's say: It works as-it-is with the older hub firmwares. As the latest hub firmware locks this project out (and noone found out yet how to downgrade the hub), I guess new features are useless until some enthusiasts builds a hub replacement.

Stupid strategy from SurePetcare in my opinion. But I don't know alternatives (and hope my hub will never die)

**Comment by plambrechtsen** [comment]
Everyone had covered it. If you are lucky enough to have a hub that hasn't been updated over 18 months ago you are able to work with it. 

But I am not really maintaining it due to work commitments and being disheartened that surepetcare locked me out of the firmware and have not provided any real alternative.

**Comment by plambrechtsen** [comment]
The alternatives are. 

- build a new hub using a Zigbee radio either the mrf24 I started building. 

- build it on a ESP32 C6. I did have a look at this but their Zigbee driver seems to be closed source and it didn't have a basic 802.14.5 packet interface unlike the MRF24 so it would be a whole new world of pain building the driver first before even getting into interfacing to the hub. 

If you're a c developer and up for a challenge then I have some code I started. You will also have an interest in reverse engineering to take the existing hub firmware and decompile some of the radio functions as there is an XOR function I never completely reverse engineered. But there is a gidra project if you're interested.

**Comment by plambrechtsen** [comment]
This code is probably going to be the only path forward once the xor key is cracked. 

https://github.com/plambrechtsen/pethublocal/tree/main/WemosPetHub

**Comment by pounard** [comment]
> Let's say: It works as-it-is with the older hub firmwares. As the latest hub firmware locks this project out (and noone found out yet how to downgrade the hub), I guess new features are useless until some enthusiasts builds a hub replacement.
> 
> Stupid strategy from SurePetcare in my opinion. But I don't know alternatives (and hope my hub will never die)

Problem is, I can't manage to install the HA addon, it always end up with an error and no logs. That's why I was asking.

Thank you all for answering!

**Comment by DataBitz** [comment]
> > Let's say: It works as-it-is with the older hub firmwares. As the latest hub firmware locks this project out (and noone found out yet how to downgrade the hub), I guess new features are useless until some enthusiasts builds a hub replacement.
> > Stupid strategy from SurePetcare in my opinion. But I don't know alternatives (and hope my hub will never die)
> 
> Problem is, I can't manage to install the HA addon, it always end up with an error and no logs. That's why I was asking.
> 
> Thank you all for answering!

You may have a conflict with another HACS integration or extension. I have had this in the past, try disabling all others and see if it starts working.

**Comment by flyize** [comment]
> > Let's say: It works as-it-is with the older hub firmwares. As the latest hub firmware locks this project out (and noone found out yet how to downgrade the hub), I guess new features are useless until some enthusiasts builds a hub replacement.
> > Stupid strategy from SurePetcare in my opinion. But I don't know alternatives (and hope my hub will never die)
> 
> Problem is, I can't manage to install the HA addon, it always end up with an error and no logs. That's why I was asking.
> 
> Thank you all for answering!

You have an old hub that has NEVER connected to the internet in the last couple of years? If your hub is recently purchased, or has been connected to the internet - don't bother as you have been locked out.

**Comment by flyize** [comment]
Your best bet is to keep an eye on this.

https://community.home-assistant.io/t/local-deployment-for-sureflap-surepetcare-connect-using-only-local-mqtt-broker/274494/558

**Comment by pounard** [comment]
> You have an old hub that has NEVER connected to the internet in the last couple of years? If your hub is recently purchased, or has been connected to the internet - don't bother as you have been locked out.

My hub is connected for 4 years~ish, so I guess I'm fucked...

**Comment by flyize** [comment]
Indeed you are. No need to waste time on this project unfortunately.

**Comment by pounard** [comment]
Thank you for answering once again. OK, I'll try to see if other projects exist. I'd love to get rid of that hub anyway.

**Comment by plambrechtsen** [comment]
I was looking to see if I could figure out flashing the old code back onto the hub @pounard . What has happened however is it is a two step process where they first flash a new bootloader on and then the new firmware.
I have a copy of the old firmware here: https://github.com/PetHubLocal/pethublocal/tree/firmware201/pethublocal/firmware but I don't have the old bootloader as the hubs are shipped with the bootloader on it. Also I haven't managed to dump the existing firmware including bootloader using a pickit so that avenue hasn't worked out.

**Comment by cintema** [comment]
Hi,
I'm more or less confused and I simply cannot figure out what the current status of the project might be.
You are describing a way to downgrade the firmware here: https://pethublocal.github.io/firmware
However, now you're writing that you couldn't work it out yet. So, what ist the current status, eventually? Is it still worth buying a hub device or is shall we rather wait for someone figuring out a reimplementation on a zigbee device (which one?) as you mentioned here:
https://github.com/plambrechtsen/pethublocal/issues/15
I feel the documentation might be outdated.
Thank you in advance!

**Comment by flyize** [comment]
This repo no longer works on hubs with newer firmware. You'll probably just want to keep an eye on this over here. There may be another company that is willing to give us local API support.

https://community.home-assistant.io/t/local-deployment-for-sureflap-surepetcare-connect-using-only-local-mqtt-broker/274494/571?u=flyize

**Comment by cintema** [comment]
Hi,
thanks for your reply. However, this device costs 500€, which is quite a bunch of money for a flap, especially if you already own a sure pet flap.
If downgrading would be doable, the older firmware should still work with pethublocal, right?

**Comment by Flachzange** [comment]
https://github.com/PetHubLocal/pethublocal/issues/29

**Comment by flyize** [comment]
> Hi, thanks for your reply. However, this device costs 500€, which is quite a bunch of money for a flap, especially if you already own a sure pet flap. If downgrading would be doable, the older firmware should still work with pethublocal, right?

Yes, but unless you're some sort of wizard, you aren't going to be able to downgrade. This project is essentially dead.

**Comment by cintema** [comment]
Isn't the entire downgrade process described here?
https://pethublocal.github.io/firmware

**Comment by flyize** [comment]
Unless you're some sort of wizard, you aren't going to be able to downgrade. This project is essentially dead.

Feel free to read around on some of the issues if you don't believe me.

**Comment by cintema** [comment]
This still doesn't exactely answer my question why there is a downgrade-description in the docs which doesn't appear to work.
However, I just managed to get a hub from ebay which is three years old but was never connected to the internet (at least according to the seller). This could maybe work then since it may run the old firmware, I guess?
Will the hub update without confirmation if connected to the internet, or is it save to play around witch it?
Thanks.

**Comment by plambrechtsen** [comment]
If the hub hasn't been plugged into the internet and upgraded in the last 3 years potentially it might still work as it's only the older firmware.
Either find a serial console and solder that on and see what comes out, or plug it into an isolated network and spin up the dns and webserver and see what you get on the first connect to the hub endpoint.
Also message me your serial number as I might have the xor key for your hub.

**Comment by Flachzange** [comment]
Ah, thanks Peter. That was also my question here: https://github.com/PetHubLocal/pethublocal/issues/28#issuecomment-2446700888

So, maybe with some luck there are  some old hubs out there

**Comment by plambrechtsen** [comment]
I do have a list of old XOR codes for a number of hubs but I think the data is useless now if the hub has been upgraded as I am sure they would have rolled or replaced the firmware key.
Send me an email if you have an old hub confirmed to be running the old firmware before the bootloader was upgraded and I can send you the necessary XOR key.

**Comment by Flachzange** [comment]
I got a hub that was not connected to the internet before (supposedly). After connecting ,I get the following output:

```
2025-01-04 17:13:41.978627+01:00File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
2025-01-04 17:13:41.978652+01:00resp = await request_handler(request)
2025-01-04 17:13:41.978662+01:00File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 543, in _handle
2025-01-04 17:13:41.978685+01:00resp = await handler(request)
2025-01-04 17:13:41.978696+01:00File "/usr/local/lib/python3.9/site-packages/pethublocal/frontend.py", line 63, in credentials
2025-01-04 17:13:41.978712+01:00firmware_version = body['firmware_version'][0]
2025-01-04 17:13:41.978721+01:00KeyError: 'firmware_version'
```

I assume this means it already has a newer bootloader. Or is that something else? Anything I can do to get some verbose output from pethublocal?

**Comment by mikeybeck** [comment]
@Flachzange I gave this a go today but am running into this error during setup - this happens after downloading the config:

```
INFO:pethublocal:Cloud Config: Download successful response: <Response [200]>
Traceback (most recent call last):
  File "/usr/local/bin/pethublocal", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pethublocal/cli/__init__.py", line 72, in setup
    pethubconfig = config_load(True, force)
  File "/usr/local/lib/python3.9/site-packages/pethublocal/functions.py", line 366, in config_load
    config.merge_update(start_to_pethubconfig(config, start))
  File "/usr/local/lib/python3.9/site-packages/pethublocal/functions.py", line 555, in start_to_pethubconfig
    device_result.merge_update({'Main_Version': str(base64.b64decode(device.version).decode('utf-8'))})
  File "/usr/local/lib/python3.9/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/local/lib/python3.9/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'int'
```

I get the same error from both the local Python setup and when using Docker.  Do I need to dig in and figure out what's gone wrong?

**Comment by mikeybeck** [comment]
Removed the base64 decoding on line 555 of functions.py and it seems like it worked ok.

Have yet to set up MQTT etc; will hopefully be able to do so tonight.

**Comment by Rouble** [comment]
This probably isn't the best place to ask this, but does anyone know if any work was done reverse engineering the communication between the wireless module and the cat door main board? I'd like to hook an esp32 up to the rf module header. 
FCC photo for reference:

![Image](https://github.com/user-attachments/assets/84e548a4-e4fa-48bd-b8e0-3d727d6c73a5)

**Comment by plambrechtsen** [comment]
Not on the Pet Door itself replacing the existing RF module. My focus was on either replacing the cloud backend using the existing hub (which I mostly achieved before SurePet pushed out new firmware locking everyone out) or building a total hub replacement and using a ESP32 + MRF32 Zigbee transmitter.

https://github.com/plambrechtsen/pethublocal/tree/main/WemosPetHub
and
https://github.com/plambrechtsen/pethublocal/tree/main/WemosMRFShield

That is where I started building a Wemos replacement until I managed to reverse engineer the hub traffic.
The only thing left to do is find out how the checksum digit is calculated. But I have the firmware in a Ghidra project just haven't found the algorithm in there.

**Comment by TheToymaker93** [comment]
> Not on the Pet Door itself replacing the existing RF module. My focus was on either replacing the cloud backend using the existing hub (which I mostly achieved before SurePet pushed out new firmware locking everyone out) or building a total hub replacement and using a ESP32 + MRF32 Zigbee transmitter.
> 
> https://github.com/plambrechtsen/pethublocal/tree/main/WemosPetHub and https://github.com/plambrechtsen/pethublocal/tree/main/WemosMRFShield
> 
> That is where I started building a Wemos replacement until I managed to reverse engineer the hub traffic. The only thing left to do is find out how the checksum digit is calculated. But I have the firmware in a Ghidra project just haven't found the algorithm in there.

@plambrechtsen First I just want to say your work on this has been legendary, I really appreciate all you've done for the community and understand if time and life commitments prevent you from responding.

My wife and I just foolishly had a SurePet Pet Door connect installed (can't return for an OnlyCat or we would) as I thought we could integrate locally after regrettably not diving deep enough into the current state of things. My bad :/

I have a reasonable development and soldering background, though at a fairly novice level in terms of C and de-compilation, however if there's any chance of getting your open-source Wemos based hub replacement working for people such as myself, I feel I owe it to the community to try.

Is there any chance you could provide more details on the current state of that side of the project? Specifically:
* It appears the hardware side is still viable, using BOM and Gerber included in the repo. Is that correct?
* You mentioned that the only thing left is to determine how a checksum digit is being calculated, and that de-compilation is a part of figuring that out. Is that related to the XOR key you've mentioned a few times? Or is the XOR only relevant when trying to get the SurePet Hub itself working?
* I presume a good start would be continuing your de-compilation efforts? Is that the case and if so, any chance you could share the project with me?
* I gather there is some form of proprietary modification to standard Zigbee between the PetDoor and the Hub that would need to be accounted for in order for this project to succeed. Do you have any inclination as to whether this is likely to be relatively minimal changes or quite significant intentional encryption in order to prevent people doing what we are trying?
* Any other advice on a good place to start, for someone just entering the project?

Once again, even if you don't respond I want to reiterate how awesome you've been doing the work you've managed and I'm sorry about the treatment you and the community have received from this company. If I could go back and support OnlyCat I would, big regret there. As it stands, the only option I have it to try limp forward the work you've begun and hopefully make progress both for myself and the community.

**Comment by plambrechtsen** [comment]
I am reviving this project and have an all new approach.
If you are interested in testing it out send me an email as I know the SurePetCare senior developer is watching this and I don't want folks to get locked out again.

**Comment by Flachzange** [comment]
Hi @plambrechtsen , also happy to support testing if needed. I still have two hubs lying around of which one is supposed to have an old (non locked) firmware version.

**Comment by plambrechtsen** [comment]
If you have a non firmware updated hub then I can help with the key for that. Then you should be able to work fine.
Send me an email with your hub serial number and I will see what I can do.

The new approach is something different and will require some soldering but nothing too difficult so I think it should be easy to do.

**Comment by Flachzange** [comment]
You've got mail. Thanks Peter!

**Comment by Geoffrey54** [comment]
Hello,

I'm interested in this addon, but i only know the firmware version of my hub :  741.84

Does this mean that i can't use the addon ?

Thanks

**Comment by plambrechtsen** [comment]
So I have a whole new approach which is in active development and coming together at pace. Send me an email pethublocal at gmail .com and I can let you know how it all works. But it will work with home assistant and completely replace the cloud service.
